### ISSUE TITLE
Probleme mit Solectrus Diagramm

### ISSUE THREAD

**Issue by wennedo** [solectrus/hosting#10]
![image](https://user-images.githubusercontent.com/118255515/205938267-c9cb529d-f6ae-4f64-bd73-5c8aee066c6d.png)

Hallo Herr Ledermann,

leider bekomme ich foglende Fehlermeldugn bei der Solectrus.

Die Daten ziehe ich mir bereits über einen Raspberry auf die Influx DB leider funktioniert die grafische Anzeige mit der IP nicht.
Haben Sie eine Idee woran es liegen kann?

**Comment by ledermann** [comment]
Da gibt es offenbar ein Problem mit dem InfluxDB-Container, der standardmäßig auf Port 8086 horcht. Der Port kann geändert werden, über die ENV-Variable `INFLUX_PORT`. Aber es sollte geprüft werden, ob es wirklich stimmt, dass der Port von etwas anderem belegt ist. Möglicherweise gibt es bereits eine InfluDB-Instanz.

**Comment by wennedo** [comment]
![image](https://user-images.githubusercontent.com/118255515/207435839-31e10e3c-889b-41a7-b88c-fa30a4ea2610.png)

![image](https://user-images.githubusercontent.com/118255515/207436241-02d3d19a-0db2-494c-a53c-5fae8cf6f40f.png)

Leider bekomme ich immer noch die Fehlermeldung ein änderung des Ports zeigt keine Wirkung.

Ich nutze einen Strato Server und komme leider nicht weiter.
Haben Sie noch einen Tipp für mich?

**Comment by wennedo** [comment]
Vielen Dank für die Antwort.

Ich habe es zwischenzeitlich zum laufen bekommen. Das System läuft jetzt korrekt und stabil. Es war tatsächlich die laufende InfluxDB die eingegrätscht hat.

Was ich mir für die Zukunft wünschen würde wäre eine Temperaturanzeige des Speicher bzw. der Gehäuses, da dies in meinem Falle wichtig zu loggen ist.
Das Einspielen der .CSV Daten lief problemlos.

Vielen Dank nochmals für den Support und das zur Verfügung stellen des Systems.

**Comment by ledermann** [comment]
Freut mich, dass es geklappt hat! 👍 

Zur Temperatur: Die Gehäuse-Temperatur wird bereits in die InfluxDB geschrieben - es fehlt "nur" noch die Anzeige im Dashboard. Siehe https://github.com/solectrus/solectrus/issues/1054
