### ISSUE TITLE
Tippfehler in Installationsanleitung

### ISSUE THREAD

**Issue by bscheufele** [solectrus/hosting#12]
Hallo Herr Ledermann,

tolles Projekt - habe es auf einem Raspberry Pi 4 installiert und einen kleinen Tippfehler in der Anleitung entdeckt:

![grafik](https://user-images.githubusercontent.com/6775549/213874881-76524e7d-9547-4b75-a3b1-f1226d7e392a.png)

raspberry-pi sollte es heißen :-)
```curl -L "https://raw.githubusercontent.com/solectrus/hosting/main/guide/raspberry-pi/docker-compose.yml" -o /home/pi/solectrus/docker-compose.yml```

Viele Grüße,
Ben

**Comment by ledermann** [comment]
Haha, besten Dank, ist korrigiert :-)
