### ISSUE TITLE
Generelles Setup Frage / InfluxDB Frage

### ISSUE THREAD

**Issue by larsxschneider** [solectrus/hosting#2]
Hi @ledermann 👋 !

Vielen Dank für Dashboard! Ich hab es installiert und folgende Frage 😊 

### Hintergrund
Initial habe ich versucht den `collector` als auch das `dashboard` auf einem Raspberry Pi zum laufen zu bekommen. Das hat nicht funktioniert weil es die InfluxDB aus dem `dashboard` docker-compose file nicht für die Pi Prozessor Architektur gibt. Danach habe ich das `dashboard` auf meinem Desktop zum laufen bekommen. Allerdings ist - soweit ich das verstehe - die InfluxDB nicht ausserhalb von Docker erreichbar. Daher habe ich es nicht geschafft den `collector` auf dem Raspberry Pi mit der InfluxDB zu verbinden. Als "hack" habe ich dann den `collector` einfach in das `dashboard` docker compose file reingenommen und so hat es dann funktioniert.

### Frage
Wie hast Du Dir das mit der InfluxDB gedacht? Hostest Du die InfluxDB selbst auf einem extra Server mit Intel CPU oder nutzt Du InfuxDB as a service im Netz?

Vielen Dank
Lars

**Comment by ledermann** [comment]
Hi Lars! Ja, die Installation ist etwas knifflig. Auf dem Raspi erfordert InfluxDB seit Version 2 ein 64bit-OS. Das lässt sich auf dem Raspi wohl auch installieren, habe ich aber selbst nie probiert. Bei mir läuft auf dem Raspi somit nur der SENEC-Collector, der die Daten im 5-Sekunden-Takt an meinen externen Server schickt, auf dem das Dashboard inklusive InfluxDB läuft.

Bei mir läuft es also wie folgt:

* Raspberry: [senec-collector/docker-compose.yml](https://github.com/solectrus/hosting/blob/main/senec-collector/docker-compose.yml), also NUR der Collector
* Externer Server (Hetzner Cloud): [dashboard/docker-compose.yml](https://github.com/solectrus/hosting/blob/main/dashboard/docker-compose.yml), der ganze Rest, also mit InfluxDB

Denkbar (aber nicht getestet) sind sicherlich auch andere Szenarien, z.B. Installation des Dashboards (ohne InfluxDB) auf dem Raspi und Nutzung von InfluxDB Cloud.

**Comment by larsxschneider** [comment]
Vielen Dank für die Info! Ich versuche mal ein docker compose file zu erstellen womit alles auf dem
Pi läuft. Würdest du das per pull request hier mergen wollen?

**Comment by ledermann** [comment]
Klar, sehr gerne. Vielleicht als Alternative zum derzeitigen Setup.
