### ISSUE TITLE
no matching manifest for linux/arm/v8 in the manifest list entries 

### ISSUE THREAD

**Issue by ChrisTheLink** [solectrus/hosting#22]
Hi, 
erst mal super vielen Dank für dieses tolle Projekt!
Ich versuche gerade es auf meinem Raspi v4 ans laufen zu bekommen, aber leider erhalte ich immer die Fehlermeldung:
"no matching manifest for linux/arm/v8 in the manifest list entries" beim docker compose, aber auch beim direkten pull der Images. 
Für influxdb, progress und redis hat es geholfen in der docker-compose.yml ein arm64v8/ for die Imagepfade zu setzen, also z.B. "image: arm64v8/influxdb:latest"

**Umgebung:**
- Linux raspberrypi 6.1.19-v8+ #1637 SMP PREEMPT Tue Mar 14 11:11:47 GMT 2023 aarch64 GNU/Linux
- Docker version 23.0.1, build a5ee5b1
- Docker Compose version v2.16.0
- REPOSITORY         TAG       IMAGE ID       CREATED        SIZE
- arm64v8/redis      latest    d7b55ece7ea9   30 hours ago   111MB
- arm64v8/influxdb   latest    d965327ac460   6 days ago     221MB
- arm64v8/postgres   latest    61d0571c2f7b   2 weeks ago    360MB
- hello-world        latest    7066d68bd2f2   2 months ago   4.85kB

Folgende Meldung erhalte ich beim compose, aber auch beim direkten pull:

```
pi@raspberrypi:~/solectrus $ docker compose up
[+] Running 0/14
 ⠋ app Pulling                                                                                                                                                         1.1s
 ⠙ senec-collector Pulling                                                                                                                                             1.1s
   ⠹ c527615e4ffa Pulling fs layer                                                                                                                                     0.2s
   ⠹ 9d609bd8ca36 Pulling fs layer                                                                                                                                     0.2s
   ⠹ 9bce405ce66f Pulling fs layer                                                                                                                                     0.2s
   ⠹ c86be2de01c4 Waiting                                                                                                                                              0.2s
   ⠹ aef28fe00a8f Waiting                                                                                                                                              0.2s
   ⠹ 82d47ab7bf96 Waiting                                                                                                                                              0.2s
   ⠹ 99697fc59c75 Waiting                                                                                                                                              0.2s
   ⠹ 4f79a30829d5 Waiting                                                                                                                                              0.2s
 ⠙ forecast-collector Pulling                                                                                                                                          1.1s
   ⠹ 77b1dacdab84 Waiting                                                                                                                                              0.2s
   ⠹ 4e1bd9e6b5b0 Waiting                                                                                                                                              0.2s
   ⠹ cc8e246de80a Waiting                                                                                                                                              0.2s
no matching manifest for linux/arm/v8 in the manifest list entries
pi@raspberrypi:~/solectrus $ docker pull ghcr.io/solectrus/solectrus:latest
latest: Pulling from solectrus/solectrus
no matching manifest for linux/arm/v8 in the manifest list entries
pi@raspberrypi:~/solectrus $ 
```

Ich komme dem Problem leider nicht auf die Spur, haben Sie noch eine Idee?
Vielen Dank und Grüße, 
Christoph

**Comment by ledermann** [comment]
Hm, ich versuche zu helfen. Bitte mal den output von `docker info`.

**Comment by ledermann** [comment]
Ursache scheint die fehlende Unterstützung für die Plattform `linux/arm/v8` zu sein, wobei ich mir noch nicht so genau darüber im Klaren bin, wie sich diese von der bereits unterstützten Plattform `linux/arm64` unterscheidet.

Ich habe soeben das SOLECTRUS-Docker-Image auch für `linux/arm/v8` erstellen lassen. @ChrisTheLink Es wäre nett, wenn Du das ausprobieren könntest. Wechsele hierzu einfach vom Docker-Tag `latest` auf `develop` und gib mir Bescheid, ob das hilft. Merkwürdig finde ich aber, dass auch die offiziellen Images für Redis, PostgreSQL und InfluxDB bei Dir nicht laufen, sondern nur die Community-Varianten von [arm64v8](https://hub.docker.com/u/arm64v8/).

Daher bin ich weiterhin sehr interessant am Output von `docker info`. Du scheinst den Linux-Kernel v6 auf dem Raspi zu haben. Der Raspi hingegen, mit dem ich SOLECTRUS teste, meldet sich so:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.16.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 9
  Running: 9
  Paused: 0
  Stopped: 0
 Images: 12
 Server Version: 23.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2456e983eb9e37e47538f59ea18f2043c9a73640
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.84-v8+
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 7.629GiB
 Name: raspberrypi
 ID: RCE4:AGLY:PBKS:JTJQ:GL6L:CZ34:T33O:S2JJ:PNJS:ERP7:RMFS:3YMO
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by ChrisTheLink** [comment]
Hi @ledermann, vielen Dank für die schnelle Antwort. Hier ist mal meine `Docker info `und in der Tat bin ich auf Kernel 6.1.19-v8+ 
Ich teste gerne die neuen Images gleich!

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.16.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 4
 Server Version: 23.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2456e983eb9e37e47538f59ea18f2043c9a73640
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.19-v8+
 Operating System: Raspbian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 3.705GiB
 Name: raspberrypi
 ID: 41082f2c-0c85-4b01-9b36-b5c0e02771df
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support

**Comment by ChrisTheLink** [comment]
Die Develop Images laufen einwandfrei. Habe nun nochmal alle Images und Container gelöscht und bin nochmal sauber am einrichten. Wen ich mit dem Test durch bin melde ich das hier zurück

**Comment by ledermann** [comment]
@ChrisTheLink Darf ich fragen, ob es mittlerweile funktioniert? Ich habe bislang keine Erfahrung mit dem Kernel v6 auf einem Raspi und es kommt nach wie vor etwas seltsam vor, dass Standard-Images wie PostgreSQL, Redis und InfluxDB aus den offiziellen Quellen darauf nicht laufen.

**Comment by ChrisTheLink** [comment]
Hi und guten Morgen,Es läuft nicht wirklich sauber, diverse Fehlermeldungen. Leider habe ich nicht rausbekommen, ob das Folgefehler waren, daher setze ich momentan einen „sauberen“ neuen Pi auf ohne mögliche Altlasten und beginne „from scratch“ und werde gerne berichten!Viele Grüße Christoph Am 24.03.2023 um 20:37 schrieb Georg Ledermann ***@***.***>:﻿
@ChrisTheLink Darf ich fragen, ob es mittlerweile funktioniert? Ich habe bislang keine Erfahrung mit dem Kernel v6 auf einem Raspi und es kommt nach wie vor etwas seltsam vor, dass Standard-Images wie PostgreSQL, Redis und InfluxDB aus den offiziellen Quellen darauf nicht laufen.

**Comment by ChrisTheLink** [comment]
Gute Nachrichten! Ich weiss nicht was genau verbastelt war, aber mit einem neuen sauberen Raspi und Einrichtung gemäß Anleitung läuft es jetzt PERFERKT :-) Ohne irgendwelche Änderungen der `docker-compose.yml` ! Danke nochmal für den Support und das tolle Projekt 💯

**Comment by ledermann** [comment]
Sehr schön! Eine Frage nur: Läuft es nur mit dem `develop` Image oder auch mit `latest`? Falls letzteres der Fall ist (so verstehe ich jedenfalls "ohne irgendwelche Änderungen der docker-compose-yml") würde ich nämlich die Plattform `linux/arm/v8` wieder rausnehmen, da es den Image-Build-Prozess verlängert.

**Comment by ChrisTheLink** [comment]
Richtig, es läuft mit latest.Am 25.03.2023 um 16:17 schrieb Georg Ledermann ***@***.***>:﻿
Sehr schön! Eine Frage nur: Läuft es nur mit dem develop Image oder auch mit latest? Falls letzteres der Fall ist (so verstehe ich jedenfalls "ohne irgendwelche Änderungen der docker-compose-yml") würde ich nämlich die Plattform linux/arm/v8 wieder rausnehmen, da es den Image-Build-Prozess verlängert.

**Comment by ledermann** [comment]
Nur der Vollständigkeit halber: 

Auf meinem Raspi ist mittlerweile der Kernel v6 über das normale `apt upgrade` Prozedere angekommen, ich habe **nicht** `rpi-update` verwendet. Er meldet sich nun so:

```
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
```

Und damit gibt es **keinerlei Probleme**. Die bestehenden Docker Images können einfach so weiter verwendet werden.
