### ISSUE TITLE
Content missing außer bei now

### ISSUE THREAD

**Issue by PatricLeidinger** [solectrus/hosting#23]
Hi, Danke für das tolle Projekt!
Ich habe es im Docker auf meiner Synology zum laufen gebracht.
Leider werden aber nur die aktuellen Daten gezeigt. 
Unter Tag, Woche etc. gibt es nur die Meldung Content missing.
Ich sehe im Log des Container solectrus_db_1 die Fehlermeldung: FATAL:  password authentication failed for user "postgres"
Es gibt auf der NAS bereits einen anderen postgres Container mit dem gleichen Port.
Kann es dadurch zu dem Problem kommen? Wie kann ich den Port ändern?

**Comment by ledermann** [comment]
Wenn Du die vorbereitete [docker-compose.yml](https://github.com/solectrus/hosting/blob/main/guide/synology/docker-compose.yml) verwendet hast, dann ist darin ein PostgreSQL-Container enthalten, der mit einem anderen PostgreSQL nicht in Konflikt gerade sollte, weil die Kommunikation der Services über ein separates Docker-Netzwerk erfolgt. Der Port `5432` kann also von mehreren Containern gleichzeitig verwendet werden, solange sie sich nicht im gleichen Netz befinden. Der Port wird übrigens auch gar nicht nach außen durchgereicht, daher kann er auch nicht geändert werden.

Was ich eher als Ursache vermute, ist ein Fehler in der ENV-Datei oder eine fehlerhafte Änderung der `docker-compose.yml`. Hinweise dazu:

- Ist die Variable `POSTGRES_PASSWORD` korrekt gesetzt? Standardmäßig hat sie den unkreativen Wert `"my-secret-db-password"`. Der String ist beliebig, darf aber nicht mehr verändert werden, wenn die Datenbank einmal existiert
- Zeigt die Variable `DB_VOLUME_PATH` auf einen existenten Ordner, der vor dem ersten Start mit `docker compose up` auch leer war?

Kannst Du mal die Logs der beiden Container `solectrus-db-1` und `solectrus-app-1` posten?

**Comment by PatricLeidinger** [comment]
Vielen Dank für den Hinweis mit dem fixen POSTGRES_PASSWORD. Da ich anfänglich Probleme mit der Firewall, dem Port für die solectrus-app-1 und dem Reverse Proxy, habe ich etwas in der docker-compose.yml herum geändert. Dabei wohl das Kennwort verbogen.
Ich habe nun einfach nochmal neu angefangen und nun funktioniert alles wie gewünscht.
