### ISSUE TITLE
Installation auf einem QNAP-System

### ISSUE THREAD

**Issue by KippA67** [solectrus/hosting#25]
Hallo zusammen,
ich möchte gerne Solectrus auf einem QNAP-TS453bmini installieren, komme da aber mit Docker & Co nicht weiter...
Gibt es da evtl. schon eine Anleitung?

Gruß
Andreas

...und mit GitHub kenn ich  mich auch nicht wirklich aus ;-))

**Comment by ledermann** [comment]
Würde mich freuen, wenn sich jemand findet, der etwas dazu sagen kann. Ich selbst habe kein QNAP zur Verfügung.

**Comment by Daedalus3** [comment]
@KippA67 im Prinzip sollte sich solectrus recht einfach über die Container Station installieren lassen (App ggf. über das App-Center laden).

Dort: Create klicken, dann auf "Create Application".

Dann: Namen eingeben und bei YAML den Inhalt der docker-compose.yml z.B. der Raspberry-Pi guide einfügen.

Validate YAML klicken, dann auf create -fertig.

Ich kann es bei mir leider nicht testen, da meine QNAP nur eine 32bit Prozessor hat. mit der TS453bmini sollte es aber klappen.

**Comment by KippA67** [comment]
Hallo und schon mal Danke für die Anleitung.
Das mit dem YAML erstellen scheint geklappt zu haben, es taucht in der Liste der Container auf.
Ich hab mal die YAML von hier genommen: "https://github.com/solectrus/hosting/blob/252b58d49e4bc351b38213834872c0666a5ba0d9/guide/raspberry-pi/docker-compose.yml"
Allerdings kommen viele Fehlermeldungen wenn ich die App starten will...
z.B. "Starting influxdb...failed" "No Containers to start1"...
Muß ich dann mit der "APP" noch weitere Schritte ausführen?

Gruß
Andreas

**Comment by ledermann** [comment]
@KippA67: Offenbar lässt sich der InfluxDB-Container nicht starten, was die Vermutung nahelegt, dass das von Dir verwendete Betriebssystem möglicherweise doch nicht 64 Bit ist. InfluxDB erfordert das aber leider zwingend.

Leider kenne ich mich mit den QNAP-Geräten überhaupt nicht aus. Aber prüfe doch mal, was `uname -a` ausgibt (in der SSH-Konsole). Da wird dann genauer ersichtlich sein, was für ein Betriebssystem bei Dir am Start ist.

**Comment by KippA67** [comment]
[~] # uname -a
Linux TS-453bmini 5.10.60-qnap #1 SMP Wed Mar 22 14:49:46 CST 2023 x86_64 GNU/Linux
[~] #

Das gibt mir das System aus (das NAS selber)

**Comment by ledermann** [comment]
Ok, Kernel v5 auf 64bit x86-Prozessor sollte funktionieren. Was genau zeigt denn Dein Docker-Logfile? Kannst Du mal den gesamten Output von `docker compose up` hier posten? Falls Du den Start anders durchführst, dann das Gegenstück aus der QNAP-Oberfläche? Irgendwo müssen Log-Zeilen herausfallen, die zur Begutachtung des Problems sehr nützlich sein werden.

**Comment by ledermann** [comment]
Was auch noch als Ursache infrage kommt: In der Anleitung gibt es einen Schritt, bei dem die Ordner für die Docker-Volumes (für PostgreSQL, Redis und InfluxDB) angelegt werden. Vielleicht hast Du das nicht gemacht? 

Außerdem ist mir nicht klar, wie Du die `.env`-Datei (mit den verschiedenen Konfigurations-Parametern) auf dem QNAP eingerichtet hast.  Beim Start der `docker-compose.yml` muss diese irgendwie mit angegeben werden. Wie das aber über die QNAP-Adminoberfläche gemacht wird, kann ich Dir leider nicht sagen.

Da Du aber bereits Docker installiert hast und auch einen SSH-Login zur Verfügung hast, würde ich einfach vorschlagen, der [Raspberry-Anleitung](https://github.com/solectrus/hosting/tree/main/guide/raspberry-pi) zu folgen und alles über die Kommandozeile zu erledigen. Einziger Unterschied vermutlich nur: Statt `/home/pi/solectrus` legst Du einen passenderen Ordner fest, gemäß dem, was QNAP so vorgibt.

**Comment by KippA67** [comment]
Danke,
ich versuch mal tiefer in das Thema einzutauchen ;-)

**Comment by KippA67** [comment]
Ich blick da nicht wirklich durch ;-)
Aber morgen bekomme ich (hoffentlich) einen Raspi und dann gibt es ja wohl keine Probleme mehr...

Danke für eure Geduld (falls ich auf dem Qnap mal eine Anleitung ausprobieren soll wäre ich dazu durchaus bereit, müsste aber "für Dummies" sein ;-)

**Comment by KippA67** [comment]
So, noch ein kleines Update:
Hab einen Pi bekommen und Solectrus ist schon installiert ;-)
Das einzige "Problem" was ich hatte war, daß bei dem "docker compose up" noch ein "sudo" davor musste..
Besten Dank nochmal für diese super Visualisierung

**Comment by ledermann** [comment]
@KippA67 Sehr schön, das freut mich :)

Um das `sudo` loszuwerden: 

```bash
sudo groupadd docker
sudo usermod -aG docker $USER
```

Nach logout & erneutem login kann man das `sudo` vor den Docker-Kommandos dann weglassen.

Details dazu: https://docs.docker.com/engine/install/linux-postinstall/
