### ISSUE TITLE
Docker-Container solectrus_app_1 wurde unerwartet gestoppt

### ISSUE THREAD

**Issue by ABreini** [solectrus/hosting#26]
Hallo,

die Installation scheint für mich als "Anfänger" mit Docker durchgelaufen zu sein. 
Jedenfalls sind alle Container vorhanden.

![Screenshot 2023-04-08 113909](https://user-images.githubusercontent.com/130217423/230714626-5ebfc821-de62-46fd-9f9f-1ad3652e32f0.png)

auch holt der collector die Daten ab und speichert sie in der Datenbank
![Screenshot 2023-04-08 114013](https://user-images.githubusercontent.com/130217423/230714638-3f1f29f8-594d-462e-8a28-2549d65f858d.png)

Mein Problem ist, dass im Docker der Container solecrus_app_1 ständig stoppt und wieder neu startet. 

![Screenshot 2023-04-08 113936](https://user-images.githubusercontent.com/130217423/230714659-79df8c2d-ef52-4662-a50b-c6bba0ebac57.png)

![Screenshot 2023-04-08 113811](https://user-images.githubusercontent.com/130217423/230714666-6d0a4378-1fca-4d8a-9ed7-fc4a62c374f7.png)

Auch kann ich das Dashboard nicht aufrufen.

Weiß jemand was da schief läuft bzw. wo ich nachschauen kann?

Grüße Brein

**Comment by ABreini** [comment]
Hab mich jetzt mal durchgesucht.

Scheint an der veralteter Kernel Version 3.XXX zu liegen. 
Dafür gibt es bis jetzt keine Lösung. 

Ich versuch es mal mit einem PI

**Comment by ledermann** [comment]
Ja, so ist es leider. Kernel muss mindestens v4 sein.
