### ISSUE TITLE
InfluxDB: Zugriff von extern

### ISSUE THREAD

**Issue by ledermann** [solectrus/hosting#27]
Hallo Ledermann,

zunächst einem vielen Dank für das tolle Projekt, es ist wirklich hilfreich!

Ich habe Probleme, über den Browser und über ioBroker auf die InfluxDB zuzugreifen. Gemäß deines Kommentares habe ich in der docker-compose.yml den Port 8086 aufgeführt.

```
# Optional: Allow InfluxDB to be accessed from the outside.
ports:
  - 8086:8086
```

Ich kann aber aber leider nicht über die Raspi IP Port 8086 (http://192.168.1.25:8086/) auf die InfluxDB zugreifen, ich bekomme nur "Die Webseite ist nicht erreichbar" angezeigt.
Woran könnte das noch liegen?

Und im Solectrus Dashboard bekomme ich unter "Jetzt" und "Top 10" alle Werte angezeigt, wenn ich auf Tag, Woche, Monat oder Jahr wechsle, wird mir "Content missing" angezeigt. Ich habe alle PV Daten der vergangenen 12 Monate via CSV importiert, diese werden unter den Top10 auch korrekt angezeigt.

Vielen Dank vorab und LG
Dominik

_Originally posted by @TheReal1988 in https://github.com/solectrus/solectrus/issues/1851#issuecomment-1500894590_

**Comment by ledermann** [comment]
@TheReal1988: Ich habe den Beitrag hierher verschoben, weil er am ursprünglichen Ort nicht passend war,

Zu 1) Prüfen, ob der Container wirklich den Port geöffnet hat. Nach einer Änderung von docker-compose.yml muss der Container neu gestartet werden, vielleicht hast Du das nicht gemacht. Was ist der Output von `docker ps`?  

Da muss ungefähr folgende Zeile stehen:
```
1f235a4375e7. influxdb:2.7-alpine. "/entrypoint.sh infl…"   29 hours ago   Up 29 hours (healthy)   0.0.0.0:8086->8086/tcp, :::8086->8086/tcp. solectrus-influxdb-1
```

Entscheidend ist das `8086->8086`.

Zu 2) Wenn im Dashboard die Meldung "Content missing" angezeigt wird (ungünstige Meldung übrigens, wird mit dem nächsten Update verbessert), dann muss man ins Docker-Log des App-Containers gucken. Da steht dann, woran es liegt. Wenn Du es selbst nicht lösen kannst, dann poste bitte den relevanten Ausschnitt aus dem Log. Ich vermute Probleme beim Zugriff auf PostgreSQL. Wir hatten kürzlich einen ähnlichen Fall (siehe #24), vielleicht helfen Dir die dortigen Kommentare.

**Comment by TheReal1988** [comment]
Vielen Dank fürs Verschieben und für die sehr hilfreichen Antworten!

Ich habe mich gestern Abend dafür entschieden, Docker mit allem Drum und Dran zu löschen und noch einmal neu zu installieren.

Inzwischen bin ich erfolgreich gewesen und kann über den Webbrowser auf die influxDB zugreifen - das ist spitze. Dort will ich mich weiter einarbeiten, um die Daten mit weiteren Messpunken (z.B. Askoma Askoheat+ Heizstab, der den Strom-Überschuss vom SENEC Speicher für die Warmwasserproduktion verwendet) kombinieren und gemeinsam auswerten.

Zum Dashboard "Content missing": Ich habe die CSV Dateien überprüft und hatte zwei Fehler. Der Post No. 24 hat mir dabei geholfen:
1) Ich habe das Installationsdatum in der .env nicht korrekt angegeben
2) Es hat sich in meinem Download Verzeichnis auf dem Rechner eine früher Excel-Datei von SENEC mit eingeschlichen. Ich habe die CSVs für jede Kalenderwoche erneut heruntergeladen und darauf geachtet, dass keine Lücken entstehen.

Schöne Ostern noch und LG
Dominik

**Comment by ledermann** [comment]
Sehr schön, vielen Dank für die Rückmeldungen! Freut mich, dass es nun funktioniert.
