### ISSUE TITLE
Aktivitätsindikator auf "FAIL", wenn Abrufintervall größer als 5 Sekunden

### ISSUE THREAD

**Issue by ThePhanThomas** [solectrus/hosting#29]
Hallo Herr Ledermann,

erst mal danke für das tolle Tool! Die Installation hat problemlos geklappt. :)

Was mir auffiel: Ich habe das Abrufintervall für die Senec-Daten von 5 Sekunden auf 1 Minute erhöht. Das klappt auch, allerdings zeigt der Aktivitätsindikator (so nenne ich das jetzt mal) oben rechts meist nur kurz den Zustand wie bspw. "Laden" an und geht dann auf FAIL, weil nach mehreren Sekunden kein Wert mehr kam. Ist die Abfrageminute rum, wird kurz wieder der tatsächliche Status angezeigt.

Viele Grüße
Thomas

**Comment by ledermann** [comment]
Prima, ich freue mich über jeden neuen User 👍 

Ja, das Problem mit "Fail" ist bekannt und dokumentiert: https://github.com/solectrus/solectrus/issues/1919
Die Implementierung steht noch aus.

Übrigens gibt es meiner Erfahrung nach keinerlei Probleme, wenn das Intervall auf 5s eingestellt ist. Bei einem Intervall von einer Minute geht ein großer Vorteil von Solectrus verloren, nämlich die Darstellung von wirklich aktuellen Messwerten. 

Außerdem dürften die verschiedenen Statistiken bei einem Intervall von einer Minute **sehr** ungenau werden, da SOLECTRUS ja nicht den Mittelwert der jeweiligen Minute erhält, sondern nur diese eine Momentaufnahme. Das ist anders als in der SENEC-App selbst: Dort wird zwar nur alle 5 Minuten gesendet, aber es handelt sich um **gemittelte** Werte. Das ist ein großer Unterschied!

**Comment by ThePhanThomas** [comment]
Vielen Dank für den Hinweis! 😊 Ich hatte das Intervall etwas höher gestellt, damit nicht dauernd auf den NAS-Platten rumgerödelt wird. Oder ist das aus deiner Sicht kein Problem? Ich weiß nicht, wie InfluxDB sich da verhält. Ansonsten probier ich's doch noch mal mit den Fünfsekundenwerten.

**Comment by ledermann** [comment]
Ob ein 5-Sekunden-Intervall die Festplatte/SSD mehr belastet, kann ich nicht aus eigener Erfahrung sagen. Denkbar ja, aber möglicherweise auch unerheblich.

Hat die Änderung des Intervalls nun geklappt? `.env`-Datei ändern und dann `docker-compose up -d` sollte genügen.
