### ISSUE TITLE
Datenbank sichern/kopieren/übertragen

### ISSUE THREAD

**Issue by Zeppelin-PV** [solectrus/hosting#30]
Ich bin Solectrus User aber kein Profi im Umgang mit Linux, Raspberry und deren OS's
Folgendes:
Ich habe zwei Raspi 4 mit Solectrus am laufen. Einfach wegen der Redundanz. Heute nacht ist einer in der Tat ausgestiegen, warum auch immer. Habe ihn mit einer Kopie des zweiten wieder zum laufen gebracht. Jetzt ist es so, dass während den Kopier und Übertragungszeiten Daten fehlen.
![grafik](https://github.com/solectrus/solectrus/assets/126392805/021ccc54-04a2-43a3-a090-79aaf92a287f)
Der zweite ist ohne diese Unterbrechungen
![grafik](https://github.com/solectrus/solectrus/assets/126392805/4679c1a1-70a7-4753-a5c7-d7ffdce4f7ee)
Frage:
gibt es eine Möglichkeit diese Lücken zu füllen mit der Datenbank des anderen. Am schönsten wäre es über das Netzwerk.
Oder mittels USB Stick ? Wie ist die richtigen Vorgehensweise ?
Danke jetzt schon für Eure Tipps.

**Comment by ledermann** [comment]
Wenn mit zwei SENEC-Collectoren der gleiche Speicher abgefragt wird, werden dabei tatsächlich **nicht** exakt gleiche Werte herauskommen. Das liegt daran, dass der Collector im 5-Sekunden-Takt eine **Momentaufnahme** abruft. Die vom Speicher gemessenen Werte ändern sich aber deutlich häufiger, vermutlich im Millisekunden-Bereich. Das ist ein kleiner Nachteil, der sich in der Praxis aber kaum auswirkt.

Im Vergleich dazu arbeitet die SENEC-App (bzw. das Portal `mein-senec.de`) ganz anders. SENEC erhält zwar nur alle 5 Minuten neue Messwerte, das sind aber vom Speicher berechnete **Durchschnittswerte** dieser 5 Minuten und daher genauer.

Meinen Erfahrungen zufolge sind die Differenzen der verschiedenen Abfragemethoden gering (< 1%).
