### ISSUE TITLE
CSV Import Anzeige fehlender Daten

### ISSUE THREAD

**Issue by metzger304** [solectrus/hosting#33]
Nach dem Import von CSV Dateien, werden diese nicht in alle in Solectrus angezeigt.

Die letzten Werte, die anzeigt werden:
- ist der Monatsansicht der 01.01.2022
- in der Wochenansicht der 24.01.2022 
- in der Tagesansicht der 27.01.2022.

Es wurde, wie in https://github.com/solectrus/csv-importer beschrieben:
- die env.  Datei mit dem richtigen Installation-Datum angepasst
- und die Redis-Cache geflusht

Die Docker Container wurden auch schon neu gestartet.

Grüße
Thomas

**Comment by ledermann** [comment]
Die `docker-compose.yml` befindet sich im gleichen Ordner wie die `.env`. Dass darin der Eintrag `INSTALLATION_DATE` fehlt, würde mich aber sehr wundern. Denn der ist in der [Originaldatei](https://github.com/solectrus/hosting/blob/main/guide/synology/docker-compose.yml) enthalten, manuell herausgenommen hast du ihn ja vermutlich nicht.

Gibt es bei dir vielleicht mehrere `.env` oder `docker-compose.yml`? Die Ordnerstruktur sollte so aussehen:

```
solectrus/
├── docker-compose.yml
├── .env
├── influxdb/
├── postgresql/
└── redis/
```

**Comment by ledermann** [comment]
`2022-01-27` ist übrigens das [Original-Beispiel](https://github.com/solectrus/hosting/blob/main/guide/synology/.env) der Anleitung. Somit dürfte die `docker-compose.yml` korrekt sein, denn es wird ja ein Wert gelesen.

Daher andere Vermutung: Heißt die `.env` bei dir womöglich anders? Sie muss wirklich `.env` heißen, also inklusive des führenden Punkts. Unter Linux führt der führende Punkt dazu, dass die Datei versteckt wird, was zu Irritationen führen könnte, wenn man das nicht weiß.

**Comment by metzger304** [comment]
> `2022-01-27` ist übrigens das [Original-Beispiel](https://github.com/solectrus/hosting/blob/main/guide/synology/.env) der Anleitung. Somit dürfte die `docker-compose.yml` korrekt sein, denn es wird ja ein Wert gelesen.
> 
> Daher andere Vermutung: Heißt die `.env` bei dir womöglich anders? Sie muss wirklich `.env` heißen, also inklusive des führenden Punkts. Unter Linux führt der führende Punkt dazu, dass die Datei versteckt wird, was zu Irritationen führen könnte, wenn man das nicht weiß.

:/volume1/docker/solectrus$  ls -a
 .   ..   csv   docker-compose.yml   .env   --env-file   influxdb   --mount  '--network=solectrus_default'   postgresql   redis

**Comment by metzger304** [comment]
![image](https://github.com/solectrus/hosting/assets/77586694/9f845376-1c06-44b1-b9c4-b509933f920a)

**Comment by ledermann** [comment]
Die drei 0-Byte-Dateien mit `--` sind überflüssig, vermutlich durch irgendwelche Fehlversuche entstanden. Bitte löschen. Ansonsten sieht es korrekt aus.

Bitte post mal die **vollständigen** Dateien `.env` und `docker-compose.yml` hier, sonst kommen wir irgendwie nicht so recht weiter.

**Comment by metzger304** [comment]
.env:
version: '3.7'

services:
  app:
    image: ghcr.io/solectrus/solectrus:latest
    depends_on:
      db:
        condition: service_healthy
      influxdb:
        condition: service_healthy
      redis:
        condition: service_healthy
    links:
      - db
      - influxdb
      - redis
    ports:
      - 3000:3000
    environment:
      - APP_HOST
      - FORCE_SSL
      - SECRET_KEY_BASE
      - INSTALLATION_DATE
      - ELECTRICITY_PRICE
      - FEED_IN_TARIFF
      - ADMIN_PASSWORD
      - DB_HOST=db
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_USER=postgres
      - REDIS_URL=redis://redis:6379/1
      - INFLUX_HOST
      - INFLUX_TOKEN=${INFLUX_TOKEN_READ}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_MEASUREMENT_PV
      - INFLUX_MEASUREMENT_FORECAST
    healthcheck:
      test: ['CMD-SHELL', 'nc -z 127.0.0.1 3000 || exit 1']
    restart: always

  influxdb:
    image: influxdb:2.7-alpine
    volumes:
      - ${INFLUX_VOLUME_PATH}:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_ADMIN_TOKEN}
    command: influxd run --bolt-path /var/lib/influxdb2/influxd.bolt --engine-path /var/lib/influxdb2/engine --store disk
    # Optional: Allow InfluxDB to be accessed from the outside.
    # ports:
    #   - 8086:8086
    restart: always
    healthcheck:
      test: ['CMD', 'influx', 'ping']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ${DB_VOLUME_PATH}:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 60s

  redis:
    image: redis:7-alpine
    volumes:
      - ${REDIS_VOLUME_PATH}:/data
    restart: always
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 60s

  senec-collector:
    image: ghcr.io/solectrus/senec-collector:latest
    depends_on:
      influxdb:
        condition: service_healthy
    links:
      - influxdb
    environment:
      - SENEC_HOST
      - SENEC_SCHEMA
      - SENEC_INTERVAL
      - INFLUX_HOST
      - INFLUX_SCHEMA
      - INFLUX_PORT
      - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_MEASUREMENT=${INFLUX_MEASUREMENT_PV}
    restart: always

  forecast-collector:
    image: ghcr.io/solectrus/forecast-collector:latest
    depends_on:
      influxdb:
        condition: service_healthy
    links:
      - influxdb
    environment:
      - INFLUX_HOST
      - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_MEASUREMENT=${INFLUX_MEASUREMENT_FORECAST}
      - FORECAST_LATITUDE
      - FORECAST_LONGITUDE
      - FORECAST_DECLINATION
      - FORECAST_AZIMUTH
      - FORECAST_KWP
      - FORECAST_INTERVAL
    restart: always

**Comment by metzger304** [comment]
.env



ee##################################################################
# Dashboard application (the main part)
#
# Domain name or IP address of your host
APP_HOST=my-synology.local
#
# SSL redirect: Use "true" if you want to auto-redirect to https, but enure that you have a valid SSL certificate
# and a reverse proxy in front of the app!
# In all other cases, the option must be "false"!
FORCE_SSL=false
#
# Secret token to secure cookies, 128 chars long hexadecimal encoded string (don't use this example, make some random changes!)
# Currently there are no cookies in Soletrus, but this may change in the future
SECRET_KEY_BASE=f60debe97dcb73280a2cc83668fd60e8d0e8e48269036a7bce980ee53cfb312e377989a750b8c945a5f69b041289ecb4e2d9e40641b81257c65ac2d43e3c837f
#
# Date of commissioning of your photovoltaic system
INSTALLATION_DATE=2020-12-13
#
# Price you pay for 1kWH (in EUR)
# Can be changed later in the UI when logged in as administrator
ELECTRICITY_PRICE=0.28
#
# Price you get for 1kWH (in EUR)
# Can be changed later in the UI when logged in as administrator
FEED_IN_TARIFF=0.0848
#
# Password for the PostgreSQL database, used by the app to comunicate internally with the database
POSTGRES_PASSWORD=my-secret-db-password
#
# Password to login as administrator, required to manage settings like historical prices
ADMIN_PASSWORD=my-secret-login-password

##################################################################
# Influx database settings
#
# Influx host (to access from SOLECTRUS dashboard and collectors)
INFLUX_HOST=influxdb
INFLUX_SCHEMA=http
INFLUX_PORT=8086
#
# Credentials for the Influx database, don't change after the first run!
INFLUX_ORG=solectrus
INFLUX_USERNAME=admin
INFLUX_PASSWORD=ExAmPl3PA55W0rD
INFLUX_ADMIN_TOKEN=my-super-secret-admin-token
#
# Set these names before first run, they can't be changed later!
INFLUX_BUCKET=my-solectrus-bucket
INFLUX_MEASUREMENT_PV=SENEC
INFLUX_MEASUREMENT_FORECAST=Forecast
#
# To keep things simple, we use ONE token (INFLUX_ADMIN_TOKEN) for both writing and reading.
# For better security, you can use two separate tokens, created via the InfluxDB frontend.
INFLUX_TOKEN_WRITE=my-super-secret-admin-token
INFLUX_TOKEN_READ=my-super-secret-admin-token
#
# Volume path for storing the Influx data
INFLUX_VOLUME_PATH=/volume1/docker/solectrus/influxdb


##################################################################
# REDIS settings
#
REDIS_VOLUME_PATH=/volume1/docker/solectrus/redis


##################################################################
# PostgreSQL database settings
#
DB_VOLUME_PATH=/volume1/docker/solectrus/postgresql


##################################################################
# SENEC Collector
#
# Change this to your own SENEC IP address!
SENEC_HOST=192.168.178.127
SENEC_SCHEMA=https
SENEC_INTERVAL=5

##################################################################
# Solar forecasting with https://forecast.solar
# API docs: https://doc.forecast.solar/doku.php?id=api:estimate
#
# Latitude of the plant location
FORECAST_LATITUDE=50.12345
#
# Longitude of the plant location
FORECAST_LONGITUDE=6.12345
#
# Plane declination: 0 (horizontal) - 90 (vertical)
FORECAST_DECLINATION=30
#
# Plane azimuth: -180 ... 180 (-180 = north, -90 = east, 0 = south, 90 = west, 180 = north)
FORECAST_AZIMUTH=20
#
# Installed modules power in kilowatt peak (kWp)
FORECAST_KWP=7.2
#
# Update interval in seconds, 900s = 15 minutes, the public (and free) API allows a minimum of 900 seconds
FORECAST_INTERVAL=900
#
# Optional damping factors (http://doc.forecast.solar/damping)
# FORECAST_DAMPING_MORNING=0.5
# FORECAST_DAMPING_EVENING=0
#
# Optional API key for registered users of forecast.solar (https://doc.forecast.solar/account_models)
# FORECAST_SOLAR_APIKEY=abc123

**Comment by metzger304** [comment]
> Die drei 0-Byte-Dateien mit `--` sind überflüssig, vermutlich durch irgendwelche Fehlversuche entstanden. Bitte löschen. Ansonsten sieht es korrekt aus.
> 
> Bitte post mal die **vollständigen** Dateien `.env` und `docker-compose.yml` hier, sonst kommen wir irgendwie nicht so recht weiter.

Sind dies persönliche Daten, die weiterverwendet / ausgelesen werden können?

**Comment by ledermann** [comment]
Ich habe deine beiden Postings der besseren Lesbarkeit editiert. Enthalten sind übrigens keinerlei persönlichen Daten, die Dateien entsprechen ja fast genau den Beispielen. Was mir dennoch auffällt:

Die `.env`-Datei beginnt mit einem `ee`. Dadurch wird ein Syntax-Fehler verursacht, was auf jeden Fall zu allen möglichen Problemen führen kann. Eigentlich müsste beim Start der Container ein Fehler gemeldet werden. Vielleicht ist der Fehler nur beim Einkopieren hier auf GitHub entstanden. Bitte prüfe das.

Ansonsten: Bist du wirklich sicher, dass deine SOLECTRUS-Container nach der `.env`-Änderung neu gestartet wurden? Was ergibt `docker-compose ps` ? Steht dort ein "Created at"-Zeitpunkt, der nach dem letzten Bearbeitungszeitpunkt der .env liegt?

Ich verstehe offen gesagt nicht so recht, was bei deiner Installation passiert ist.

**Comment by metzger304** [comment]
:/volume1/docker/solectrus$ docker-compose ps
             Name                           Command                  State               Ports
-------------------------------------------------------------------------------------------------------
solectrus_app_1                  docker/startup.sh                Up (healthy)   0.0.0.0:3000->3000/tcp
solectrus_db_1                   docker-entrypoint.sh postgres    Up (healthy)   5432/tcp
solectrus_forecast-collector_1   /bin/sh -c bundle exec app ...   Up
solectrus_influxdb_1             /entrypoint.sh influxd run ...   Up (healthy)   8086/tcp
solectrus_redis_1                docker-entrypoint.sh redis ...   Up (healthy)   6379/tcp
solectrus_senec-collector_1      /bin/sh -c bundle exec app ...   Up

wie lautet der Befehl um created at abzufragen?

Snip:
die ee###### ... stehen in der dritten Zeile
![image](https://github.com/solectrus/hosting/assets/77586694/2ccfdc16-ed5e-4f96-9707-ac926404c43d)

**Comment by ledermann** [comment]
Wenn in deiner `.env` dieses `ee` drin steht, dann ist das ein **fataler** Fehler. Bitte korrigiere das. In einer `.env` muss **jede** Zeile entweder eine Variablen-Definition der Art `FOO=42` enthalten oder ein Kommentar sein (beginnend mit `#`). 

Dass bei dir das Kommando `docker-compose ps` nicht das Erstellungsdatum des Containers ausgibt, wundert mich. Bei mir (Synology DS220+ mit Docker 20.10) ist das so. Egal, versuche mal `docker ps`.

Meine Vermutung ist nun folgende:

- Du hast SOLECTRUS installiert und zum Laufen gebracht. Alles funktioniert.
- Du hast dann die CSV-Dateien importiert. Das hat auch funktioniert.
- Du hast dann die .env bearbeitet und `INSTALLATION_DATE` verändert. Beim Speichern der Datei ist dann etwas schiefgegangen, wodurch unbemerkt die zwei `e` am Anfang der Datei eingefügt wurden.
- Du hast dann versucht, die Container neu zu starten. Wegen der fehlerhaften `.env` klappte das aber nicht, es gab nur eine Fehlermeldung, die aber nicht beachtet wurde. Der Neustart der Container hat gar nicht stattgefunden.

Somit laufen die alten Container mit alten ENV-Variablen seit längerem einfach weiter. Die Änderung ist also gar nicht aktiv.

Abhilfe:

1. `.env` korrigieren
2. Container neu starten (mit `docker-compose down`, dann `docker-compose up -d`)
3. Fertig

**Comment by metzger304** [comment]
PERFEKT.. vielen lieben Dank

ich denke, es wird so sein wie du es gesagt hast.. als ich das erstes mal (überhaupt) die env. Datein über die Konsole bearbeitet habe, habe ich das wohl aus versehen eingetragen... (habe danach auch erst die Befehle gegoogled, sorry...

Ist ein Bearbeiten auch über den Editor in der Synology genauso wirksam?

Auszug nun vom dem Instatlations Datum

docker exec solectrus_app_1 env | grep INSTALLATION_DATE
**INSTALLATION_DATE=2020-12-13** 

Snip Solectrus APP

![image](https://github.com/solectrus/hosting/assets/77586694/5acb5f81-1a70-46e6-938c-2406d6b7ea08)

Donation wurde auch getätigt!

**Comment by ledermann** [comment]
Prima, freut mich sehr, dass es geklappt hat!

Ja, die beiden Dateien (`.env` und `docker-compose.yml`) können auch über den Text-Editor von Synology bearbeitet werden. Standardmäßig zeigt der aber nur Textdateien (also *.txt) beim Öffnen an, man muss dort also auf "Alle Dateien" umstellen. Ich denke, das werde ich auch so in der Anleitung beschreiben, der Editor `vim` ist vom Bedienkomfort katastrophal.

Das kannst du direkt mal ausprobieren 😄  - weil ja noch ein paar andere Parameter in der `.env` eingestellt werden sollten (insbesondere FORECAST_* ganz unten).

**Comment by ledermann** [comment]
Nur der Vollständigkeit halber: Der Text-Editor **wird** bereits in der Anleitung erwähnt 😄 

https://github.com/solectrus/hosting/blob/1e714495d48b6425e8e7ed2054b89a6d96c59517/guide/synology/README.md?plain=1#L90
