### ISSUE TITLE
CSV Import - Fehlende Daten

### ISSUE THREAD

**Issue by DennisM84** [solectrus/hosting#34]
Hallo zusammen,
vielleicht hat ja jemand eine Idee woran es liegen kann das ich nur Daten aus 2023 habe und die aus 2022 fehlen.

Ich habe gestern Docker auf einer Debian 12 VM unter Proxmox aufgesetzt und dann Solectrus installiert. Ich habe dabei das Installations Datum falsch interpretiert und auf 09.09.2023 gesetzt.

Solectrus läuft soweit super. Übrigens wirklich spitzen Arbeit. Daumen hoch.

Ich habe dann im Anschluß die ganzen CSV Exporte gezogen und pro Jahr in einem Ordner abgelegt. Den Import Befehl wie in der Doku beschrieben ausgeführt und auch den dortigen Befehl um den Cache zurück zu setzen. Dann festgestellt das ich das falsche Installations Datum gesetzt habe, es in der .env angepasst und nochmals Import und Cache Befehle ausgeführt. Alles aus 2023 ist drin, die Werte aus 2022 fehlen wie gesagt.

Jemand eine Idee??

Danke euch schon jetzt für eure Unterstützung.

**Comment by ledermann** [comment]
@DennisM84 Freut mich, dass dir SOLECTRUS gefällt 😄 

Was genau meinst du damit, dass "die Werte aus 2022" fehlen? Sind die entsprechenden Summen leer oder kannst du auf die Zeiträume aus 2022 nicht navigieren?

Möglicherweise hast du vergessen, nach Änderung der `.env`-Datei die Container neu zu starten.

Eine Änderung von `INSTALLATION_DATE` macht es übrigens **nicht** erforderlich, die CSV-Dateien erneut zu importieren, das ist unabhängig davon.

Ansonsten bitte mal in #33 nachlesen, da ging es um ähnliche Probleme.

**Comment by DennisM84** [comment]
Ich konnte im UI die Werte nicht auf 2022 stellen.

Aber auch hier war ein ähnlicher Fehler, die Container wurden nach dem Import und ändern des Installations Datum nicht neu erstellt. Das Installations Datum war noch falsch. 

Habe dann die Container mit den beiden Befehlen im dir verlinkten Eintrag neu geschrieben/gestartet und nun sind die Werte aus 2022 auch drin.

Danke dir für die schnelle und unkomplizierte Hilfe 😊

**Comment by ledermann** [comment]
😄
