### ISSUE TITLE
SOLECTRUS nicht mehr erreichbar

### ISSUE THREAD

**Issue by ledermann** [solectrus/hosting#37]
> habe gestern morgen das Update (wie gehabt nach Deiner Anleitung) auf die 14.2 gemacht - soweit so gut, lief auch alles zunächst.
> Plötzlich nachmittags zeigte Solectrus "Keine Verbindung" oben rechts. Also Log aktualisiert weil ich dachte der übliche NPU-Fehler - im Log war aber nichts zu sehen, also runter in den Keller - Verbindung am Speicher steht. Also nochmal sudo reboot und docker ps probiert - scheint alles zu laufen. Aber ich kann weder über die lokale IP noch über meine dynDNS auf meine Daten zugreifen (solectrus öffnet sich nicht mehr). Ich habe aber nichts am Router verändert, am Raspberry seit dem Update auf 14.2 auch nicht mehr. Die lokale IP kann ich anpingen im Heimnetzwerk - was kann ich tun ? Mein Senec und die Senec-App laufen also der V3 liefert Daten (log geht auch). Also stimmt irgendwas am Raspberry nicht !? Kann ich noch mehr testen um den Fehler einzugrenzen ? Ich verzweifel ohne mein Solectrus unterwegs :(

_Originally posted by @OnkelMF in https://github.com/solectrus/solectrus/discussions/2710#discussioncomment-8078640_

**Comment by OnkelMF** [comment]
Werde ich machen wenn ich heute nach Hause komme - ich danke Dir :)

**Comment by ledermann** [comment]
Ok, der App-Container läuft gar nicht, sondern startet wohl immer wieder neu ("Restarting"). Demnach sind die Logs wichtig, da wird der Grund zu sehen sein. Mit folgendem Kommando lassen sich die letzten 100 Zeilen ausgeben:

```
docker logs solectrus-app-1 --tail 100
```

Mehr zum Logging:
https://docs.docker.com/engine/reference/commandline/logs/

**Comment by ledermann** [comment]
Die relevante Zeile ist die hier:

```
A server is already running (pid: 1, file: /app/tmp/pids/server.pid).
``` 

War hier vielleicht ein Stromausfall o.ä. im Spiel? Versuche mal folgendes:

```
docker compose down
docker rm solectrus-app-1
docker compose up -d
```
https://docs.docker.com/engine/reference/commandline/rm/

Damit wird der Container gelöscht (und damit sein `tmp`-Ordner). Beim nächsten Start sollte es dann wieder funktionieren.

Ansonsten noch härter diese Möglichkeit:

```
docker compose down
docker system prune
docker compose up -d
```
https://docs.docker.com/engine/reference/commandline/system_prune/

**Comment by OnkelMF** [comment]
Hallo Georg, 

eigentlich gab es keinen Ausfall. Ich saß ja am Mac als plötzlich „keine Verbindung“ erschien. Danach hab ich den Raspy aus und wieder angeschaltet aber das Problem lies sich nicht lösen. Sind nach Deiner Methode die alten Daten weg oder bleibt das bisherige Datenmaterial vorhanden ? Wäre schade sonst 😉

**Comment by ledermann** [comment]
"Keine Verbindung" klingt nach der Status-Anzeige von SOLECTRUS. Wenn die erscheint, kommen keine Daten mehr in InfluxDB an - SOLECTRUS selbst läuft aber weiterhin.

"Raspi aus und wieder an" könnte aber die Ursache sein, zumindest wenn du das auf die harte Tour mit dem Power-Schalter gemacht hast. Auch ein Raspi will korrekt heruntergefahren werden.

Zu meinem Vorschlag: Nein, da geht nichts verloren. Wenn der Container gelöscht wird (mit `docker rm`), dann sind nur temporäre Dinge weg, das ist völlig unkritisch. Alles Wichtige steckt in den Volumes von PostgreSQL und InfluxDB. 
Der zweite Vorschlag mit `docker system prune` löscht zwar mehr, aber auch nichts Kritisches. Genaueres findet sich in den beiden Links.

**Comment by OnkelMF** [comment]
hmm das Verzeichnis kann ich irgendwie nicht löschen:
 
Error response from daemon: No such container: solectrus-app-1

egal ob im Verzeinis Solectrus oder im Root-Verzeichnis.

Aber allein 

docker compose down und dann docker compose up -d

haben das Problem gelöst - wo auch immer es her kam ich kann wieder an mein Solectrus und bin glücklich !

Danke !!

**Comment by ledermann** [comment]
Prima, freut mich! 

Nur als Ergänzung: Mit `docker rm` wird kein Verzeichnis gelöscht, sondern ein beendeter Docker-Container. Ich bin irgendwie davon ausgegangen, dass du ein "down & up" bereits versucht hattest. Denn mit `docker compose down` werden normalerweise auch die Container gelöscht.
