### ISSUE TITLE
Senec Collector

### ISSUE THREAD

**Issue by wennedo** [solectrus/hosting#39]
Hallo Herr Ledermann,

mein Senec Collector zeigt folgenden Fehler an:

"Error getting record from SENEC at 192.168.178.61: failed to connect: Connection refused - connect(2) for "192.168.178.61" port 80"

Das Senec Schema passt mit https, wenn ich über den Rechner darauf zugreifen möchte, kommt diese Seite ist nicht sicher. 

Was kann ich tun damit die Werte gezogen werden?

Danke & Gruß
D.Wenzel

**Comment by wennedo** [comment]
Ich habe das System heute neu aufgesetzt, es war recht lange auf der To Do 

Der Server sagt "service "senec-collector" is not running"
Der Pi sagt: "no configuration file provided: not found"

**Comment by wennedo** [comment]
SENEC collector for SOLECTRUS
https://github.com/solectrus/senec-collector
Copyright (c) 2020,2022 Georg Ledermann, released under the MIT License

Using Ruby 3.1.3 on platform arm-linux-musleabihf
Pulling from SENEC at 192.168.178.61 every 5 seconds
Pushing to InfluxDB at http://85.214.246.9:8086, bucket solectrus

Error getting record from SENEC at 192.168.178.61: failed to connect: Connection refused - connect(2) for "192.168.178.61" port 80

**Comment by wennedo** [comment]
mit ghcr.io/solectrus/senec-collector:develop bekomme ich die Werte

**Comment by ledermann** [comment]
Neu aufgesetzt ok, aber die Ausgabe des Collectors zeigt eine uralte Programmversion aus 2022. Da hatte ich noch gar keine Versionierung eingeführt ;-)

Unterstützung für https gibt es beim Collector erst seit 2023. Das ist also der Grund. Daher bitte immer ":latest" Tag verwenden. Für alle Container. Besser nicht ":develop", das sind Entwicklerversionen.

**Comment by wennedo** [comment]
Ich hatte 2022 schon einmal probiert es zu installieren und aus Zeitmangel habe ich es hinten angestellt.
Wenn ich auf :latest wechsle bekomme ich den bekannten Fehler

**Comment by ledermann** [comment]
Es muss natürlich ein `docker compose pull` erfolgen, damit das neue "latest"-Image auch heruntergeladen wird. Docker verwendet ansonsten das lokal vorhandene Image. Und das ist hier offenbar veraltet.

**Comment by ledermann** [comment]
Seit 2022 hat sich bei SOLECTRUS so viel getan, auch die Anleitung habe ich in vielerlei Hinsicht verbessert. Am besten ist, wirklich ganz neu anfangen und insbesondere die aktuellen heute angebotenen `.env` und `docker-compose.yml` verwenden, siehe hier:
https://github.com/solectrus/hosting/tree/main/guide/raspberry-pi

**Comment by wennedo** [comment]
Server seitig habe ich komplett neu aufgesetzt.

Wo muss ich den compose pull wie machen?

**Comment by ledermann** [comment]
Alle `docker compose` Befehle werden in dem Ordner ausgeführt, der eine `docker-compose.yml` enthält. Ein `docker compose pull` sucht dann für alle Images, die in der Datei referenziert werden, eine aktuellere Version. Das ist sehr zu empfehlen.

**Comment by wennedo** [comment]
Leider kann ich auf dem Raspberry kein docker compose pull ausführen.
/ $ docker compose pull
[+] Pulling 4/7
 ✘ db Error                                                                1.0s
 ✘ redis Error                                                             1.0s
 ⠏ senec-collector Pulling                                                 1.0s
 ⠏ app Pulling                                                             1.0s
 ✘ watchtower Error                                                        1.0s
 ⠏ forecast-collector Pulling                                              1.0s
 ✘ influxdb Error                                                          1.0s
no matching manifest for linux/arm/v8 in the manifest list entries

**Comment by ledermann** [comment]
Es sieht so aus, als wäre der Raspi mit 32bit-Architektur unterwegs.

Bitte mal das hier prüfen:
```
name -m
```

Die Ausgabe **MUSS** `aarch64` lauten. Falls nicht, muss der Raspi mit einem 64bit-Linux neu aufgesetzt werden.

Ein ähnliches Thema hatten wir hier schon mal:
https://github.com/solectrus/hosting/issues/28#issuecomment-1511671081

**Comment by wennedo** [comment]
Danke, habe es hinbekommen.
