### ISSUE TITLE
Fehler: Keine Verbindung - warum?

### ISSUE THREAD

**Issue by Nemo3006** [solectrus/hosting#42]
Hallo!
Ich habe heute vermutlich einen blöden Fehler begangen. Ich wollte ein Backup meiner Speicherkarte aus dem Raspi machen. Hab den Raspi heruntergefahren, ausgeschaltet, ApplePiBaker die Karte geklont und wieder eingesetzt. Raspi wieder hochgefahren. Ab da lief leider gar nichts mehr. Mein solectrus zeigt oben rechts immer "Keine Verbindung" an und einen roten Punkt daneben. Was kann ich tun? Ich war so froh dass alles lief und nun hab ich mir vermutlich irgendwas zerschossen -.-

**Comment by ledermann** [comment]
Ich sehe in diesem Vorgehen eigentlich nicht Falsches.

Offenbar läuft das Dashboard, aber es kommen keine Daten in InfluxDB. 

Läuft der SENEC-Collector-Container? (`docker ps`)
Falls ja, stehen Fehlermeldungen in den Logs? (`docker compose logs senec-collector`, ausführen im Ordner, in dem die `docker-compose.yml` liegt)

**Comment by Nemo3006** [comment]
Danke für deine Antwort. Das werde ich sofort testen wenn ich zu Hause bin. Ich habe gar nicht erwähnt dass ich die Variante mit Hetzner, also mit Zugriff von außen habe. Das könnte ja auch noch eine Ursache sein.

**Comment by ledermann** [comment]
Auf Hetzner läuft dann vermutlich das Dashboard und die Datenbanken. Die funktionieren offenbar, sonst hättest du ein ganz anderes Fehlverhalten. 

Der SENEC-Collector liefert in deinem Fall offenbar keine Daten an die InfluxDB. Das kann viele Gründe haben. Der SENEC-Collector-Container und dessen Logs sind daher die erste Anlaufstelle.

**Comment by Nemo3006** [comment]
Also wenn ich "Docker ps" eingebe kommt `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

Wo müsste ich denn die Docker-compose finden? Also wenn ich ganz genau nach Anleitung vorgegangen bin?

**Comment by ledermann** [comment]
Dein Docker-Daemon läuft gar nicht, mit der `docker-compose.yml` hat das erst mal nichts zu tun. Der Docker-Daemon ist ein Hintergrunddienst, der permanent laufen muss, wenn du irgendwas mit Docker machen willst. Warum der Daemon nicht läuft, kann ich nicht sagen, manuell starten kannst du ihn meist mit:

```
sudo systemctl start docker
```

Damit das auch nach einem Reboot passiert, könnte das hier helfen:

```
sudo systemctl enable docker
```

Genaueres ist in der Docker-Doku nachzulesen:
https://docs.docker.com/engine/install/debian/

**Comment by Nemo3006** [comment]
hm... wenn ich das eingebe kommt `sudo systemctl start docker
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.`

**Comment by ledermann** [comment]
Ja, komische Sache. Da kann ich dir ehrlicherweise auch nicht wirklich weiterhelfen. 

Voraussetzungen für SOLECTRUS ist, dass Docker funktionsfähig ist. Das musst du irgendwie selber hinbekommen. Die beiden von der Fehlermeldung erwähnten Kommandos würde ich mal ausprobieren und hoffen, dass es dadurch weitere Hinweise gibt. 

Möglicherweise könnte eine erneute Docker-Installation helfen (siehe mein Link oben). Dein Raspi ist momentan jedenfalls nicht korrekt konfiguriert für Docker, das hat mit SOLECTRUS gar nichts zu tun.

**Comment by Nemo3006** [comment]
Am einfachsten wäre es sicherlich, wenn ich den raspi neu aufsetze oder? Danke dir auf jeden Fall für deine Unterstützung

**Comment by ledermann** [comment]
Ja, wenn sonst nichts darauf läuft, ist das wirklich einfach. Und sicherer. Es bleibt nur unklar, was das Problem überhaupt ausgelöst hat.

**Comment by Nemo3006** [comment]
Nein, ich habe noch EVCC und ioBroker, aber die laufen auf einem anderen Raspi. Ich melde mich, wenn ich alles neu aufgesetzt habe.

**Comment by Nemo3006** [comment]
Update: Jetzt läuft wieder alles. Danke für deine Hilfe, Georg! Wie immer: TOP!
