### ISSUE TITLE
Multiple forecast collectors / orientations

### ISSUE THREAD

**Issue by unclej84** [solectrus/hosting#5]
Hello,

is it possible to use the inhouse setup with 2 forecast selectors for different orientations and module powers or does one override the other then? Best would be to have them added to a total forecast.

Regards Jörg

**Comment by ledermann** [comment]
This is a feature which is still missing in [forecast-collector](https://github.com/solectrus/forecast-collector). I've added added an issue for this to implement later: solectrus/forecast-collector#64

Meanwhile, you could take a look at another Solectrus user's project that solved this exact issue:
https://github.com/jbaesner/quarkus-forecast-collector/
