### ISSUE TITLE
Solectrus zeiugt Ständig "Keine Verbindung"  aber es werden trotzdem aktuelle Werte angezeigt

### ISSUE THREAD

**Issue by jacitty** [solectrus/hosting#50]
Seit ein paar Wochen sehe ich ständig "Keine Verbindung" aber es werden die aktuellen Werte angezeigt. 
![solectrus_keine-verbindung](https://github.com/solectrus/solectrus/assets/143817789/ec83a42a-01c2-49c1-9d9d-bda1c9ef7207)

**Comment by ledermann** [comment]
Habe das Issue mal verschoben, es geht hier ja eher um ein Installationsproblem.

**Comment by jacitty** [comment]
Hallo.
Das von dir beschriebene Lastbild kann ich hier nachvollziehen. Raspi an sich langweilt sich großteils, bei 'docker stats' geht die CPU für die InfluxDB alle paar Sekunden mal auf rund 11%. Ich denke ich versuche es mal mit einer anderen SD-Karte. Da bruach ich aber jetzt erstmal ein wenig.

**Comment by ledermann** [comment]
Ok, gucke aber vorher mal in die Logs der InfluxDB. Im Normalfall ist dort wenig los. Wenn es wirklich an der SD-Karte liegt, müsste die InfluxDB Probleme beim Schreiben haben und das (vermutlich) im Log protokollieren. Wenn nicht, dann bin ich ratlos. Austausch der SD-Karte würde ich dann (mangels anderer Ideen) wohl dennoch mal versuchen.

**Comment by jacitty** [comment]
Ich habe jetzt einfach mal die SD-Karte geklont und mit dem Klon neu gestartet. Also anscheinend hat die alte Karte wirklich einen Schlag gehabt (Tests laufen noch), denn alleine das Booten des Raspi war viel schneller. Das 'docker compose up -d ' dauerte, bis bei allen Containern "Started" stand, insgesamt 4,4 Sekunden. Mit der alten Karte waren es hier Werte zwischen 20 und 60 Sekunden. Da muss also was mit der Karte faul gewesen sein. Fehler in den DB-Logs konnte ich jedoch keine finden, warum auch immer. Jetzt sind auch bereits seit mehr als einer Stunde keine Error-Einträge mehr beim Collector-Container aufgetreten, so wie es aussieht war es die SD-Karte.

Danke für die schnelle und so umfangreiche Hilfe, ich denke ich habe heute wieder einiges dazu gelernt. Watchtower läuft jetzt auch mit und das Backup-Skript ist ebenfalls fertig, es fehlt nur noch die Auslagerung aufs NAS.

**Comment by ledermann** [comment]
Wohl dem, der immer eine zweite SD-Karte in der Schublade hat :) Danke für die Rückmeldung! Freut mich, dass eine Lösung gefunden wurde.
