### ISSUE TITLE
Verlinkung in Home-Assistant Seitenleiste

### ISSUE THREAD

**Issue by deThommy** [solectrus/hosting#52]
Hallo zusammen,

ich finde die Darstellung von SOLECTRUS mega und möchte diese auch in meiner Home Assistant (HA) Seitenleiste verlinken, damit ich das alles direkt an einem Ort habe. Ich mag die SOLECTRUS Darstellung deutlich lieber, als die von HA.

Soweit so einfach: ich gebe die interne IP von SOLECTRUS samt Port als Link eines neuen Dashboards an. Jetzt sollte das schon funktionieren (geht mit EVCC genau so synology.local:7070. Zu SOLECTRUS (synology.local:3000) kann allerdings keine Verbindung aufgebaut werden. 

Ich gehe sogar stark davon aus, dass das ein Problem bei mir intern ist, weiß aber nicht, wo ich anfangen soll, zu suchen. 

Ergibt das für euch Sinn? EVCC und SOLECTRUS laufen auf derselben Synology, beide auch per Docker. Funktioniert so alles perfekt zusammen, aber einbinden kann ich die interne IP nicht? Ist da noch irgendein Port dazwischen den ich freigeben müsste oder? Eigentlich darf hier intern alles kommunizieren.

Hat jemand eine Idee, wonach ich suchen kann? Jeder Tipp hilft. Danke!

**Comment by ledermann** [comment]
Ja, iFrame-Einbettung wird standardmäßig von SOLECTRUS abgelehnt, die muss vorher freigeschaltet werden.

Setze die Variable `FRAME_ANCESTORS` auf die URL deiner HA-Installation:
https://github.com/solectrus/solectrus/wiki/Konfiguration#erweiterte-einstellungen

Danach noch prüfen, ob `FRAME_ANCESTORS` auch in der `docker-compose.yml` unter `services.app.environment` vorhanden ist (ggfs. ergänzen), dann `docker compose down && docker compose up -d`.

**Comment by deThommy** [comment]
Perfekt, dann lag es wohl doch nur "indirekt" an mir :) Habe die Werte soweit ergänzt. Ein einfacher Neustart des Solectrus Containers geht offenbar nicht?

Ich navigiere immer über das GUI bzw. den Container Manager.

>  dann `docker compose down && docker compose up -d`.

Kann ich das dann auch irgendwie über das GUI triggern? Über den Terminal des Containers kann ich das nicht eingeben?

**Comment by ledermann** [comment]
Ich weiß nicht genau, was Synology unter "Neustart" versteht. In der Docker-Terminologie muss der Container jedenfalls neu erstellt werden, `docker stop` und `docker start` genügt explizit **nicht**. 

Probiere es einfach aus: Welche Variablen ein Container kennt, kannst du im UI sehen (Tab "Allgemein", runterscrollen bis "Umgebungsvariablen").

**Comment by deThommy** [comment]
Hat geklappt. 

Konnte die Variable schnell über das UI ändern (das hatte ich auch gemacht). Und in der Yaml hab ichs händisch ergänzt. Anschließend den Container wieder gestartet. Dann tauchte es im HA auf!
