### ISSUE TITLE
Darstellung Ladestand E-Auto

### ISSUE THREAD

**Issue by deThommy** [solectrus/hosting#55]
Hallo Georg,

ich habe gerade die neuen Sensoren für den Ladestand des E-Autos konfiguriert, dabei ist mir aufgefallen, dass die Darstellung im iframe (HomeAssisant) von der Darstellung direkt über SOLECTRUS abweicht, siehe nachfolgende Screenshots.

Ist nicht wirklich störend, aber schadet sicherlich nicht zu wissen?! :) 

Viele Grüße und danke fürs Weiterentwickeln!

Darstellung im iFrame:
<img width="660" alt="Darstellung im iFrame" src="https://github.com/user-attachments/assets/eaa66d90-f293-4cca-ae41-368bf2a48061">

Darstellung auf der Website selbst:
<img width="601" alt="Darstellung auf der Website selbst" src="https://github.com/user-attachments/assets/809e39c3-2623-4d36-89e3-e9b70a65737c">

**Comment by ledermann** [comment]
Wenn du SOLECTRUS in verschiedenen Browser-Fenstern/Tabs/Frames oder verschiedenen Geräten (Desktop/Tablet/Phone) parallel öffnest, aktualisieren sich diese unabhängig voneinander. Alle haben zwar das gleiche Intervall (eingestellt über `INFLUX_POLL_INTERVAL`, default ist 5 Sekunden), aber sie starten ja nicht zur exakt gleichen Zeit. Während der eine Browser die Darstellung gerade aktualisiert hat, folgt der andere vielleicht eine Sekunde später.

Alles korrekt, soweit ich das sehe :)
