### ISSUE TITLE
Question: Purpose of Postgres-DB

### ISSUE THREAD

**Issue by unclej84** [solectrus/hosting#6]
Hello,

I wanted to integrate the stack into my existing environment (redis and postgres are already running). What is the purpose of the postgres db and which database name is it using? `solectrus_production`?

Thanks in advance for your feedback.

**Comment by ledermann** [comment]
Currently, the PostgreSQL database is **not** used by Solectrus, but it must be present when the application is started. And yes, the name of the database is `solectrus_production`. 

I plan to use the database in the future for configuration data and electricity prices.
