### ISSUE TITLE
Error on In-house instructions

### ISSUE THREAD

**Issue by moe-king** [solectrus/hosting#7]
On point to you need to change the instructions to create a dashboard folder under the solectrus folder. Otherwise it will post some errors when runinng the docker-compose up.

Here the corrected version for point 2:

ssh [YOUR-SERVER-IP-ADDRESS]
cd /volume1/docker
mkdir solectrus
cd solectrus
mkdir dashboard
cd dashboard
mkdir redis postgresql influxdb

**Comment by ledermann** [comment]
Good catch, thanks a lot!
