### ISSUE TITLE
Error getting record from SENEC at 192.168.xxx.xxx: 301 "Moved Permanently"

### ISSUE THREAD

**Issue by Twooearly** [solectrus/hosting#8]
Hey,
Ich habe soeben den "Solectrus" Docker Container exakt wie beschrieben heruntergeladen und installiert. Das Webinterface funktioniert prinzipiell auch, nur zeigt es keine Daten an. 
Könnte es daran liegen, dass unser Speicher ein Konto mit Passwort hat? Oder brauche ich trotz dem Homeserver einen Raspberry Pi?
Hier noch einmal den exakten Text aus den Docker Logs:

`senec-collector_1     | Error getting record from SENEC at 192.168.xxx.xxx: 301 "Moved Permanently` 

Dies nur mehrmals hintereinander, falls es hilft, angehängt auch ein Screenshot aus der Konsole: 
![Screenshot 2022-10-22 112437](https://user-images.githubusercontent.com/82608982/197331903-1d56ba19-b85a-4272-973d-84acf0dfbf12.png)

Ich benutze einen alten PC als Server, auf dem die neuste Version von Ubuntu mit allen verfügbaren Updates läuft. Die Docker und Docker-compose Pakete sind alle auf dem neusten Stand.

Gibt es irgendwelche Lösungsvorschläge? Vielen Dank im Voraus!
Felix

**Comment by ledermann** [comment]
Die Lösung ist recht einfach: In der Datei `.env` muss die richtige IP-Adresse des SENEC-Speichers eingetragen werden. Da steht standardmäßig nur `192.168.xxx.xxx`. Trage dort die Adresse ein, die im Display des Speichers angezeigt wird.

Ansonsten noch:
- Der Speicher selbst ist nicht mit einem Passwort geschützt (im Gegensatz zu mein-senec.de)
- Ein Raspberry wird nur dann benötigt, wenn es sonst im Haus keinen Server gibt, auf dem der SENEC-Collector laufen könnte. In Deinem Fall ist also **kein** Raspberry nötig

**Comment by Twooearly** [comment]
Vielen Dank für die schnelle Antwort! Etwas unaufmerksam von mir...
Und auch Danke für die weiterführenden Antworten!
